export type ProductType = 'software' | 'website' | 'open-source' | 'book' | 'course' | 'kids'

export type Product = {
  id: string
  slug: string
  title: string
  type: ProductType
  category: string
  price: number
  oldPrice?: number
  rating: number
  reviewsCount: number
  thumbnail: string
  gallery: string[]
  description: string
  features: string[]
  tags: string[]
  author: string
  language: string
  level?: string
  ageRange?: string
  pages?: number
  duration?: string
  lessons?: number
  version?: string
  stars?: number
  forks?: number
  license?: string
  isFree: boolean
  isFeatured?: boolean
  createdAt: string
  accent: string
}

const pics = (id: string) => `https://picsum.photos/seed/${id}/400/300`
const galleryPics = (id: string) => [
  `https://picsum.photos/seed/${id}-a/800/600`,
  `https://picsum.photos/seed/${id}-b/800/600`,
  `https://picsum.photos/seed/${id}-c/800/600`,
]

export const products: Product[] = [
  // SOFTWARE 7 — $19-149
  {
    id: 'sw-01',
    slug: 'regex-visual-debugger',
    title: 'Regex Visual Debugger',
    type: 'software',
    category: 'Software',
    price: 39,
    oldPrice: 59,
    rating: 4.7,
    reviewsCount: 842,
    thumbnail: pics('sw-01'),
    gallery: galleryPics('sw-01'),
    description: 'See your regular expressions run in real time. Paste a pattern, test strings instantly, and get plain-English explanations for every group. Built for developers who debug regex weekly.',
    features: ['Live match highlighting with capture groups', 'Plain-English breakdown of each token', 'Export to JS/Python/Go snippets', 'Dark mode and offline support', 'One-time purchase, free updates'],
    tags: ['developer-tools', 'regex', 'debugging'],
    author: 'Jordan Lee',
    language: 'English',
    version: '2.4.1',
    isFree: false,
    isFeatured: true,
    createdAt: '2023-03-14',
    accent: '#635BFF',
  },
  {
    id: 'sw-02',
    slug: 'iconflow-for-figma',
    title: 'Iconflow for Figma',
    type: 'software',
    category: 'Software',
    price: 49,
    rating: 4.8,
    reviewsCount: 412,
    thumbnail: pics('sw-02'),
    gallery: galleryPics('sw-02'),
    description: 'Stop hunting for icons. Search 120k+ icons from one panel, drop them as vectors, and keep styles in sync. Teams use it to cut icon review time in half.',
    features: ['Search across Phosphor, Lucide and Heroicons', 'Auto-color to your Figma styles', 'Batch replace icons in selection', 'Save favorites to shared libraries', 'Works offline after first sync'],
    tags: ['figma-plugin', 'icons', 'design-systems'],
    author: 'Mira Patel',
    language: 'English',
    version: '1.9.3',
    isFree: false,
    isFeatured: false,
    createdAt: '2024-01-22',
    accent: '#14B8A6',
  },
  {
    id: 'sw-03',
    slug: 'tidy-windows',
    title: 'Tidy Windows — macOS Window Manager',
    type: 'software',
    category: 'Software',
    price: 19,
    oldPrice: 29,
    rating: 4.5,
    reviewsCount: 1240,
    thumbnail: pics('sw-03'),
    gallery: galleryPics('sw-03'),
    description: 'Snap, stack and hide windows with keyboard shortcuts you will actually remember. Designed for people who live in too many tabs.',
    features: ['10 snap layouts + custom grids', 'Hide all but current window in one keystroke', 'Remember layouts per display', 'No subscription, no account', 'Under 8 MB, native Swift'],
    tags: ['macos', 'productivity', 'window-manager'],
    author: 'Calvin Wu',
    language: 'English',
    version: '3.1.0',
    isFree: false,
    isFeatured: false,
    createdAt: '2023-07-08',
    accent: '#F59E0B',
  },
  {
    id: 'sw-04',
    slug: 'pixel-port-theme-pack',
    title: 'Pixel Port — VS Code Theme Pack',
    type: 'software',
    category: 'Software',
    price: 29,
    rating: 4.6,
    reviewsCount: 560,
    thumbnail: pics('sw-04'),
    gallery: galleryPics('sw-04'),
    description: 'Five calm themes tuned for long coding sessions. Low contrast for comments, clear contrast for code. Your eyes will notice on day two.',
    features: ['Light, dark and OLED variants', 'Italic options for comments/keywords', 'Matches for 20+ product fonts', 'Terminal color sync', 'Lifetime license'],
    tags: ['vs-code', 'themes', 'developer-tools'],
    author: 'Sofia Lind',
    language: 'English',
    version: '2.0.4',
    isFree: false,
    isFeatured: false,
    createdAt: '2024-06-11',
    accent: '#F43F5E',
  },
  {
    id: 'sw-05',
    slug: 'plaintext-crm',
    title: 'PlainText CRM for Indie Founders',
    type: 'software',
    category: 'Software',
    price: 149,
    oldPrice: 199,
    rating: 4.3,
    reviewsCount: 187,
    thumbnail: pics('sw-05'),
    gallery: galleryPics('sw-05'),
    description: 'A CRM that feels like a spreadsheet, not a sales funnel. Track conversations, follow-ups and deals without the overhead your team hates.',
    features: ['CSV-first: import/export in one click', 'Threads view for every contact', 'Reminders that stay in menu bar', 'Self-hosted option included', '30-day money back'],
    tags: ['crm', 'indie-hackers', 'productivity'],
    author: 'Ben Ortiz',
    language: 'English',
    version: '4.2.0',
    isFree: false,
    isFeatured: false,
    createdAt: '2023-11-03',
    accent: '#635BFF',
  },
  {
    id: 'sw-06',
    slug: 'loomline-async-notes',
    title: 'Loomline — Async Video Notes',
    type: 'software',
    category: 'Software',
    price: 79,
    rating: 4.4,
    reviewsCount: 320,
    thumbnail: pics('sw-06'),
    gallery: galleryPics('sw-06'),
    description: 'Record a short loop, add frame notes, and share a link. Less meeting time, clearer feedback. Used by design teams who work across time zones.',
    features: ['Record tab, window or camera', 'Draw on frames, time-stamped comments', 'Transcription with search', 'Notion/Slack embeds', 'Unlimited viewers'],
    tags: ['async-video', 'collaboration', 'remote-work'],
    author: 'Aisha Khan',
    language: 'English',
    version: '1.8.2',
    isFree: false,
    isFeatured: false,
    createdAt: '2024-09-19',
    accent: '#14B8A6',
  },
  {
    id: 'sw-07',
    slug: 'schema-buddy',
    title: 'Schema Buddy — Database Diagram Kit',
    type: 'software',
    category: 'Software',
    price: 99,
    rating: 4.6,
    reviewsCount: 210,
    thumbnail: pics('sw-07'),
    gallery: galleryPics('sw-07'),
    description: 'Sketch your schema before you migrate. Drag tables, draw relations, and generate Postgres/Prisma code. Keep the diagram next to the PR.',
    features: ['Postgres, MySQL and Prisma export', 'Auto-layout with manual tweak', 'Share as live link or PNG', 'Version history per diagram', 'Figma-like shortcuts'],
    tags: ['database', 'diagramming', 'developer-tools'],
    author: 'Ravi Singh',
    language: 'English',
    version: '1.4.0',
    isFree: false,
    isFeatured: false,
    createdAt: '2025-02-11',
    accent: '#F59E0B',
  },

  // WEBSITES 5 — $29-99
  {
    id: 'web-01',
    slug: 'stellar-saas-landing-kit',
    title: 'Stellar SaaS — Landing Kit for Next.js',
    type: 'website',
    category: 'Websites',
    price: 89,
    rating: 4.7,
    reviewsCount: 642,
    thumbnail: pics('web-01'),
    gallery: galleryPics('web-01'),
    description: 'A complete marketing site for your SaaS. Pricing, changelog, docs and blog are already wired. Ships with Tailwind and MDX.',
    features: ['Next.js 14 + App Router', '12 landing sections, fully responsive', 'Stripe pricing toggle', 'MDX blog and docs', 'Lighthouse 98+'],
    tags: ['nextjs', 'saas', 'landing-page'],
    author: 'Studio Orbit',
    language: 'English',
    isFree: false,
    isFeatured: true,
    createdAt: '2024-03-02',
    accent: '#635BFF',
  },
  {
    id: 'web-02',
    slug: 'folio-mono-portfolio',
    title: 'Folio Mono — Portfolio for Creatives',
    type: 'website',
    category: 'Websites',
    price: 49,
    rating: 4.5,
    reviewsCount: 380,
    thumbnail: pics('web-02'),
    gallery: galleryPics('web-02'),
    description: 'A single-page portfolio that puts work first. Big images, quiet type, no bloat. Perfect for photographers and illustrators.',
    features: ['One-page smooth scroll', 'CMS-ready project loader', 'Lightbox with keyboard nav', 'No jQuery, 12 kB CSS', 'Deploy to Vercel in 2 clicks'],
    tags: ['portfolio', 'minimal', 'nextjs'],
    author: 'Maya Brooks',
    language: 'English',
    isFree: false,
    isFeatured: false,
    createdAt: '2023-05-18',
    accent: '#F43F5E',
  },
  {
    id: 'web-03',
    slug: 'inkpress-webflow-agency',
    title: 'Inkpress — Webflow Agency Template',
    type: 'website',
    category: 'Websites',
    price: 69,
    oldPrice: 89,
    rating: 4.6,
    reviewsCount: 290,
    thumbnail: pics('web-03'),
    gallery: galleryPics('web-03'),
    description: 'An agency site that lets case studies do the talking. Editorial grid, client logos and a contact flow that actually converts.',
    features: ['CMS Collections for work + team', 'Client logo marquee', 'Contact with Calendly embed', 'Style guide included', 'Webflow Figma source'],
    tags: ['webflow', 'agency', 'editorial'],
    author: 'Atelier 47',
    language: 'English',
    isFree: false,
    isFeatured: false,
    createdAt: '2024-08-05',
    accent: '#14B8A6',
  },
  {
    id: 'web-04',
    slug: 'shelf-shopify-minimal',
    title: 'Shelf — Shopify Minimal Store',
    type: 'website',
    category: 'Websites',
    price: 59,
    rating: 4.4,
    reviewsCount: 410,
    thumbnail: pics('web-04'),
    gallery: galleryPics('web-04'),
    description: 'A Shopify theme for stores that sell fewer, better products. Fast filters, real reviews and a calm checkout.',
    features: ['OS 2.0 sections everywhere', 'Mega-menu with images', 'Sticky add-to-cart on scroll', 'Shopify 8.0 compatible', 'Under 50 kB JS'],
    tags: ['shopify', 'ecommerce', 'minimal'],
    author: 'Kindred Digital',
    language: 'English',
    isFree: false,
    isFeatured: false,
    createdAt: '2023-09-22',
    accent: '#F59E0B',
  },
  {
    id: 'web-05',
    slug: 'typecraft-astro-blog',
    title: 'Typecraft — Astro Blog Starter',
    type: 'website',
    category: 'Websites',
    price: 29,
    rating: 4.8,
    reviewsCount: 520,
    thumbnail: pics('web-05'),
    gallery: galleryPics('web-05'),
    description: 'A fast, readable blog starter for Astro. Ships with RSS, OG images and a type scale you can tweak in one file.',
    features: ['Astro 4 + Content Collections', 'Auto OG image generation', 'RSS + sitemap', '100/100 Lighthouse', 'No JS by default'],
    tags: ['astro', 'blog', 'content'],
    author: 'Field School',
    language: 'English',
    isFree: false,
    isFeatured: false,
    createdAt: '2025-01-15',
    accent: '#635BFF',
  },

  // OPEN SOURCE 6 — all FREE (price 0)
  {
    id: 'os-01',
    slug: 'drift-sync',
    title: 'Drift Sync — Local-first Sync Engine',
    type: 'open-source',
    category: 'Open Source',
    price: 0,
    rating: 4.9,
    reviewsCount: 2100,
    thumbnail: pics('os-01'),
    gallery: galleryPics('os-01'),
    description: 'A tiny sync engine for local-first apps. Persists to IndexedDB, syncs in the background, resolves conflicts with CRDTs.',
    features: ['< 9 kB gzipped', 'IndexedDB + WebSocket sync', 'CRDT conflict resolution', 'Works offline first', 'TypeScript first'],
    tags: ['local-first', 'sync', 'crdt'],
    author: 'Onyx Community',
    language: 'English',
    stars: 12800,
    forks: 1200,
    license: 'MIT',
    isFree: true,
    isFeatured: true,
    createdAt: '2023-02-10',
    accent: '#14B8A6',
  },
  {
    id: 'os-02',
    slug: 'termblazer',
    title: 'TermBlazer — Fast Terminal File Manager',
    type: 'open-source',
    category: 'Open Source',
    price: 0,
    rating: 4.6,
    reviewsCount: 980,
    thumbnail: pics('os-02'),
    gallery: galleryPics('os-02'),
    description: 'Navigate, preview and bulk-rename without leaving the terminal. Feels like Finder for people who live in the shell.',
    features: ['Vim keys + preview pane', 'Bulk rename with regex', 'Git status inline', 'Cross-platform', 'No config needed'],
    tags: ['terminal', 'file-manager', 'rust'],
    author: 'Adam Argyle',
    language: 'English',
    stars: 8400,
    forks: 530,
    license: 'MIT',
    isFree: true,
    isFeatured: false,
    createdAt: '2023-06-19',
    accent: '#F59E0B',
  },
  {
    id: 'os-03',
    slug: 'mockline',
    title: 'Mockline — HTTP Mocking for JS',
    type: 'open-source',
    category: 'Open Source',
    price: 0,
    rating: 4.5,
    reviewsCount: 740,
    thumbnail: pics('os-03'),
    gallery: galleryPics('os-03'),
    description: 'Mock fetch and axios with a single wrapper. Define routes once, reuse in tests and local dev. No service worker required.',
    features: ['Fetch/axios intercept', 'Delay and error simulation', 'Record and replay', 'Vitest/Jest helpers', 'Type-safe mocks'],
    tags: ['http', 'mocking', 'testing'],
    author: 'Motion Community',
    language: 'English',
    stars: 6200,
    forks: 310,
    license: 'MIT',
    isFree: false,
    isFeatured: false,
    createdAt: '2024-02-28',
    accent: '#635BFF',
  },
  {
    id: 'os-04',
    slug: 'deckdown',
    title: 'Deckdown — Markdown Slides CLI',
    type: 'open-source',
    category: 'Open Source',
    price: 0,
    rating: 4.4,
    reviewsCount: 520,
    thumbnail: pics('os-04'),
    gallery: galleryPics('os-04'),
    description: 'Write slides in Markdown, present in the terminal or export to PDF. Good for conference talks and quick decks.',
    features: ['Markdown to slides', 'Terminal presenter', 'PDF export', 'Code highlight', 'Live reload'],
    tags: ['markdown', 'slides', 'cli'],
    author: 'Tauri Contributors',
    language: 'English',
    stars: 4100,
    forks: 240,
    license: 'Apache-2.0',
    isFree: false,
    isFeatured: false,
    createdAt: '2024-05-12',
    accent: '#F43F5E',
  },
  {
    id: 'os-05',
    slug: 'tunnelhop',
    title: 'Tunnelhop — Webhook Tunnel',
    type: 'open-source',
    category: 'Open Source',
    price: 0,
    rating: 4.7,
    reviewsCount: 690,
    thumbnail: pics('os-05'),
    gallery: galleryPics('os-05'),
    description: 'Expose localhost with a public URL. Forward webhooks, inspect requests, and share a preview without deploying.',
    features: ['One command tunnel', 'Request inspector', 'Custom subdomains', 'Works behind NAT', 'Self-hostable'],
    tags: ['tunnel', 'webhooks', 'devtools'],
    author: 'PocketBase Team',
    language: 'English',
    stars: 5400,
    forks: 180,
    license: 'MIT',
    isFree: false,
    isFeatured: false,
    createdAt: '2023-10-04',
    accent: '#14B8A6',
  },
  {
    id: 'os-06',
    slug: 'statepeek',
    title: 'StatePeek — React State Debugger',
    type: 'open-source',
    category: 'Open Source',
    price: 0,
    rating: 4.6,
    reviewsCount: 810,
    thumbnail: pics('os-06'),
    gallery: galleryPics('os-06'),
    description: 'See Zustand/Jotai/Redux state change over time. Time-travel, diff and export traces for bug reports.',
    features: ['Zustand & Redux adapters', 'Time-travel debugger', 'Diff view', 'Export trace JSON', 'DevTools extension'],
    tags: ['react', 'debugging', 'state'],
    author: 'Vercel Community',
    language: 'English',
    stars: 7300,
    forks: 420,
    license: 'MIT',
    isFree: false,
    isFeatured: false,
    createdAt: '2024-11-03',
    accent: '#635BFF',
  },

  // BOOKS 10 — $9-39
  {
    id: 'bk-01',
    slug: 'the-creative-habit',
    title: 'The Creative Habit',
    type: 'book',
    category: 'Online Books',
    price: 29,
    rating: 4.7,
    reviewsCount: 842,
    thumbnail: pics('bk-01'),
    gallery: galleryPics('bk-01'),
    description: 'A field guide to keeping creative work moving on ordinary days. Twyla Tharp shares rituals, prompts and stories from 30 years of making.',
    features: ['32 daily rituals you can try', 'Stories from rehearsal to performance', 'Prompts for when you feel stuck', 'Short chapters, easy to revisit', 'EPUB + PDF included'],
    tags: ['creativity', 'habits', 'craft'],
    author: 'Twyla Tharp',
    language: 'English',
    pages: 256,
    isFree: false,
    isFeatured: false,
    createdAt: '2023-04-11',
    accent: '#F59E0B',
  },
  {
    id: 'bk-02',
    slug: 'shipping-side-projects',
    title: 'Shipping Side Projects',
    type: 'book',
    category: 'Online Books',
    price: 19,
    oldPrice: 29,
    rating: 4.5,
    reviewsCount: 610,
    thumbnail: pics('bk-02'),
    gallery: galleryPics('bk-02'),
    description: 'Turn small ideas into shipped products without burning weekends. A practical playbook from makers who launched 30+ projects.',
    features: ['Scope to one weekend', 'Pricing and launch checklist', 'Interviews with 12 indie makers', 'Templates for landing + emails', 'Honest failure notes'],
    tags: ['indie', 'shipping', 'makers'],
    author: 'Leah Osei',
    language: 'English',
    pages: 208,
    isFree: false,
    isFeatured: false,
    createdAt: '2023-08-20',
    accent: '#14B8A6',
  },
  {
    id: 'bk-03',
    slug: 'pragmatic-typescript',
    title: 'Pragmatic TypeScript',
    type: 'book',
    category: 'Online Books',
    price: 34,
    rating: 4.8,
    reviewsCount: 920,
    thumbnail: pics('bk-03'),
    gallery: galleryPics('bk-03'),
    description: 'TypeScript without the theory slog. Learn the 20% of the type system that fixes 80% of bugs, with real code you can copy.',
    features: ['Narrowing and guards in practice', 'Typing legacy JS incrementally', 'Generics you will actually use', 'Exercises per chapter', 'Covers TS 5.4'],
    tags: ['typescript', 'javascript', 'programming'],
    author: 'Mason Riley',
    language: 'English',
    pages: 320,
    isFree: false,
    isFeatured: true,
    createdAt: '2024-02-14',
    accent: '#635BFF',
  },
  {
    id: 'bk-04',
    slug: 'design-systems-in-practice',
    title: 'Design Systems in Practice',
    type: 'book',
    category: 'Online Books',
    price: 39,
    oldPrice: 49,
    rating: 4.6,
    reviewsCount: 540,
    thumbnail: pics('bk-04'),
    gallery: galleryPics('bk-04'),
    description: 'How teams ship consistent interfaces without slowing down. Tokens, components and governance told through three real redesigns.',
    features: ['Token architecture that scales', 'Component API design', 'Documentation that gets read', 'Figma + code sync', 'Case studies from 3 teams'],
    tags: ['design-systems', 'ui', 'workflow'],
    author: 'Amina Bell',
    language: 'English',
    pages: 280,
    isFree: false,
    isFeatured: false,
    createdAt: '2023-12-05',
    accent: '#F43F5E',
  },
  {
    id: 'bk-05',
    slug: 'clean-architecture-notes',
    title: 'Clean Architecture Notes',
    type: 'book',
    category: 'Online Books',
    price: 24,
    rating: 4.4,
    reviewsCount: 430,
    thumbnail: pics('bk-05'),
    gallery: galleryPics('bk-05'),
    description: 'Short notes on boundaries, dependencies and testing. Read it in an afternoon, refer to it for a year.',
    features: ['Boundaries without jargon', 'Testing at the edges', 'When to extract a module', 'Diagrams, not just code', 'PDF + EPUB'],
    tags: ['architecture', 'clean-code', 'backend'],
    author: 'Jonas Hart',
    language: 'English',
    pages: 240,
    isFree: false,
    isFeatured: false,
    createdAt: '2024-07-16',
    accent: '#635BFF',
  },
  {
    id: 'bk-06',
    slug: 'writing-that-ships',
    title: 'Writing That Ships',
    type: 'book',
    category: 'Online Books',
    price: 14,
    rating: 4.3,
    reviewsCount: 380,
    thumbnail: pics('bk-06'),
    gallery: galleryPics('bk-06'),
    description: 'Write the update, doc or README people actually read. Structure, tone and revision in 30 minutes a day.',
    features: ['The inverted pyramid for product writing', 'Before/after passages', 'Voice and tone cheat sheet', 'Revision checklist', 'Email course included'],
    tags: ['writing', 'communication', 'product'],
    author: 'Parker Miles',
    language: 'English',
    pages: 160,
    isFree: false,
    isFeatured: false,
    createdAt: '2025-03-08',
    accent: '#F59E0B',
  },
  {
    id: 'bk-07',
    slug: 'the-quiet-manager',
    title: 'The Quiet Manager',
    type: 'book',
    category: 'Online Books',
    price: 22,
    oldPrice: 32,
    rating: 4.5,
    reviewsCount: 510,
    thumbnail: pics('bk-07'),
    gallery: galleryPics('bk-07'),
    description: 'Lead without the performance. A calm approach to one-on-ones, feedback and decisions for first-time managers.',
    features: ['One-on-one agenda templates', 'Feedback that sticks', 'Decision logs', 'Stories from small teams', 'Print-ready worksheets'],
    tags: ['management', 'leadership', 'teams'],
    author: 'Noor Rahman',
    language: 'English',
    pages: 212,
    isFree: false,
    isFeatured: false,
    createdAt: '2023-10-18',
    accent: '#14B8A6',
  },
  {
    id: 'bk-08',
    slug: 'photo-light',
    title: 'Photo Light — Seeing in Color',
    type: 'book',
    category: 'Online Books',
    price: 26,
    rating: 4.6,
    reviewsCount: 290,
    thumbnail: pics('bk-08'),
    gallery: galleryPics('bk-08'),
    description: 'Learn to see light before you touch the camera. Shape, shadow and color through exercises you can do on a walk.',
    features: ['30 exercises, no gear needed', 'Color palettes from photos', 'Before/after light studies', 'Print tips for color', '192 pages, hardcover PDF'],
    tags: ['photography', 'color', 'visual'],
    author: 'Inez Okafor',
    language: 'English',
    pages: 192,
    isFree: false,
    isFeatured: false,
    createdAt: '2024-09-01',
    accent: '#F43F5E',
  },
  {
    id: 'bk-09',
    slug: 'gradual-finance',
    title: 'Gradual Finance — Money Habits',
    type: 'book',
    category: 'Online Books',
    price: 18,
    rating: 4.2,
    reviewsCount: 340,
    thumbnail: pics('bk-09'),
    gallery: galleryPics('bk-09'),
    description: 'Small money habits that compound. Saving, spending and investing explained without hype or jargon.',
    features: ['The 2-account system', 'How to automate saving', 'Investing basics in plain English', 'Worksheets included', 'Updated 2024 edition'],
    tags: ['finance', 'habits', 'money'],
    author: 'Cleo Park',
    language: 'English',
    pages: 160,
    isFree: false,
    isFeatured: false,
    createdAt: '2025-05-20',
    accent: '#635BFF',
  },
  {
    id: 'bk-10',
    slug: 'build-in-public-handbook',
    title: 'Build in Public Handbook',
    type: 'book',
    category: 'Online Books',
    price: 16,
    rating: 4.4,
    reviewsCount: 470,
    thumbnail: pics('bk-10'),
    gallery: galleryPics('bk-10'),
    description: 'Share your work as you make it. Templates for updates, threads and launch posts that sound like you.',
    features: ['30 prompt cards for updates', 'Thread and video outlines', 'Launch day checklist', 'Examples from real founders', 'Notion template'],
    tags: ['building-in-public', 'writing', 'founders'],
    author: 'The Common Thread',
    language: 'English',
    pages: 144,
    isFree: false,
    isFeatured: false,
    createdAt: '2024-04-27',
    accent: '#F59E0B',
  },

  // KIDS 8 — $4.99-24.99
  {
    id: 'kd-01',
    slug: 'luna-and-the-sleepy-moon',
    title: 'Luna and the Sleepy Moon',
    type: 'kids',
    category: 'Kids Room',
    price: 9.99,
    rating: 4.8,
    reviewsCount: 640,
    thumbnail: pics('kd-01'),
    gallery: galleryPics('kd-01'),
    description: 'A bedtime story about a girl who helps the moon find its blanket. Soft rhymes, warm art, and a calm ending.',
    features: ['32 pages, read-aloud 6 min', 'Watercolor art', 'Print + PDF', 'Free audio narration', 'Ages 3-5'],
    tags: ['storybook', 'bedtime', 'ages-3-5'],
    author: 'Lulu House',
    language: 'English',
    ageRange: '3-5',
    pages: 32,
    isFree: false,
    isFeatured: false,
    createdAt: '2024-01-10',
    accent: '#F59E0B',
  },
  {
    id: 'kd-02',
    slug: 'milos-dino-draw-along',
    title: "Milo's Dino Draw-Along",
    type: 'kids',
    category: 'Kids Room',
    price: 12,
    rating: 4.7,
    reviewsCount: 410,
    thumbnail: pics('kd-02'),
    gallery: galleryPics('kd-02'),
    description: 'Draw 12 friendly dinosaurs step by step. Each lesson adds one shape until the dino appears. No perfection needed.',
    features: ['12 video lessons, 2-4 min each', 'Printable tracing sheets', 'Crayon-friendly', 'Share gallery included', 'Ages 6-8'],
    tags: ['drawing', 'dinosaurs', 'ages-6-8'],
    author: 'Poppy Studio',
    language: 'English',
    ageRange: '6-8',
    pages: 48,
    isFree: false,
    isFeatured: true,
    createdAt: '2023-08-15',
    accent: '#14B8A6',
  },
  {
    id: 'kd-03',
    slug: 'block-math-games',
    title: 'Block Math — Games with Blocks',
    type: 'kids',
    category: 'Kids Room',
    price: 15,
    rating: 4.5,
    reviewsCount: 280,
    thumbnail: pics('kd-03'),
    gallery: galleryPics('kd-03'),
    description: 'Build, count and compare with wooden-block games. A playful first course for kids who like to move while they learn.',
    features: ['10 games, 5 min each', 'No screen needed for play', 'Parent guide included', 'Progress stickers', 'Ages 6-8'],
    tags: ['math', 'blocks', 'ages-6-8'],
    author: 'Brightside Learning',
    language: 'English',
    ageRange: '6-8',
    duration: '1h 20m',
    lessons: 10,
    isFree: false,
    isFeatured: false,
    createdAt: '2024-03-18',
    accent: '#635BFF',
  },
  {
    id: 'kd-04',
    slug: 'scratch-jr-first-games',
    title: 'Scratch Jr. — First Games',
    type: 'kids',
    category: 'Kids Room',
    price: 24.99,
    oldPrice: 34.99,
    rating: 4.6,
    reviewsCount: 310,
    thumbnail: pics('kd-04'),
    gallery: galleryPics('kd-04'),
    description: 'Make a chase game and a dance party in Scratch Jr. Drag blocks, add sprites, and share the game with family.',
    features: ['22 lessons, 3-5 min each', 'No typing needed', 'Make 2 shareable games', 'Tablet friendly', 'Ages 9-12'],
    tags: ['scratch', 'coding', 'ages-9-12'],
    author: 'Pixel Pals',
    language: 'English',
    ageRange: '9-12',
    duration: '3h 15m',
    lessons: 22,
    isFree: false,
    isFeatured: false,
    createdAt: '2023-12-12',
    accent: '#F43F5E',
  },
  {
    id: 'kd-05',
    slug: 'reading-adventures-level-1',
    title: 'Reading Adventures Level 1',
    type: 'kids',
    category: 'Kids Room',
    price: 14,
    rating: 4.4,
    reviewsCount: 260,
    thumbnail: pics('kd-05'),
    gallery: galleryPics('kd-05'),
    description: 'Short stories with big type and picture clues. Kids read a page, answer one question, and earn a star.',
    features: ['20 stories, 50-80 words each', 'Phonics-friendly', 'Star chart', 'Audio for each story', 'Ages 6-8'],
    tags: ['reading', 'phonics', 'ages-6-8'],
    author: 'The Story Club',
    language: 'English',
    ageRange: '6-8',
    pages: 64,
    isFree: false,
    isFeatured: false,
    createdAt: '2024-06-22',
    accent: '#F59E0B',
  },
  {
    id: 'kd-06',
    slug: 'garden-of-little-stars',
    title: 'Garden of Little Stars',
    type: 'kids',
    category: 'Kids Room',
    price: 7.99,
    rating: 4.7,
    reviewsCount: 180,
    thumbnail: pics('kd-06'),
    gallery: galleryPics('kd-06'),
    description: 'A gentle story about a garden that grows when you share it. For quiet mornings and bedtime.',
    features: ['24 pages', 'Calm rhymes', 'Seek-and-find art', 'Free coloring PDF', 'Ages 3-5'],
    tags: ['storybook', 'nature', 'ages-3-5'],
    author: 'Wild Wonder',
    language: 'English',
    ageRange: '3-5',
    pages: 24,
    isFree: false,
    isFeatured: false,
    createdAt: '2025-02-03',
    accent: '#14B8A6',
  },
  {
    id: 'kd-07',
    slug: 'mayas-rocket-diary',
    title: "Maya's Rocket Diary",
    type: 'kids',
    category: 'Kids Room',
    price: 11,
    rating: 4.5,
    reviewsCount: 210,
    thumbnail: pics('kd-07'),
    gallery: galleryPics('kd-07'),
    description: 'Maya builds a cardboard rocket and writes about the flight. A journal-story for kids who love space and doodles.',
    features: ['28 pages with journal prompts', 'Space facts on each spread', 'Draw-your-planet pages', 'Ages 9-12', 'Print + PDF'],
    tags: ['space', 'journal', 'ages-9-12'],
    author: 'Luna Press',
    language: 'English',
    ageRange: '9-12',
    pages: 28,
    isFree: false,
    isFeatured: false,
    createdAt: '2024-10-11',
    accent: '#635BFF',
  },
  {
    id: 'kd-08',
    slug: 'colour-mix-lab',
    title: 'Colour Mix Lab',
    type: 'kids',
    category: 'Kids Room',
    price: 0,
    rating: 4.9,
    reviewsCount: 520,
    thumbnail: pics('kd-08'),
    gallery: galleryPics('kd-08'),
    description: 'Mix colors with finger paint logic, no mess. A free play lab for 3-5s to learn primary and secondary colors.',
    features: ['Drag to mix colors', 'No ads, no account', 'Works on tablet', 'Save mixing as image', 'Free forever'],
    tags: ['colors', 'play', 'ages-3-5'],
    author: 'Wonder Works',
    language: 'English',
    ageRange: '3-5',
    pages: 12,
    isFree: true,
    isFeatured: false,
    createdAt: '2023-05-03',
    accent: '#F59E0B',
  },

  // COURSES 8 — $19-199
  {
    id: 'co-01',
    slug: 'calculus-i-limits-to-derivatives',
    title: 'Calculus I — Limits to Derivatives',
    type: 'course',
    category: 'Student Courses',
    price: 149,
    oldPrice: 199,
    rating: 4.6,
    reviewsCount: 840,
    thumbnail: pics('co-01'),
    gallery: galleryPics('co-01'),
    description: 'From intuitive limits to confident derivatives. Visual proofs, practice sets and a midterm you can retry until it clicks.',
    features: ['12 hours video', '42 lessons + 6 problem sets', 'Visual limit explorer', 'Midterm with retry', 'Certificate included'],
    tags: ['calculus', 'math', 'university'],
    author: 'Dr. Amara Wells',
    language: 'English',
    duration: '12h 00m',
    lessons: 42,
    level: 'Intermediate',
    isFree: false,
    isFeatured: false,
    createdAt: '2023-09-10',
    accent: '#635BFF',
  },
  {
    id: 'co-02',
    slug: 'python-for-absolute-beginners',
    title: 'Python for Absolute Beginners',
    type: 'course',
    category: 'Student Courses',
    price: 99,
    rating: 4.8,
    reviewsCount: 2100,
    thumbnail: pics('co-02'),
    gallery: galleryPics('co-02'),
    description: 'Write your first programs in a weekend. Loops, functions and files taught through small projects you will actually finish.',
    features: ['20 hours, 48 lessons', 'Build 3 mini apps', 'Auto-graded exercises', 'No setup: browser IDE', 'Community Q&A'],
    tags: ['python', 'beginners', 'coding'],
    author: 'Eli Morgan',
    language: 'English',
    duration: '20h 00m',
    lessons: 48,
    level: 'Beginner',
    isFree: false,
    isFeatured: true,
    createdAt: '2023-04-02',
    accent: '#14B8A6',
  },
  {
    id: 'co-03',
    slug: 'physics-mechanics-crash-course',
    title: 'Physics: Mechanics Crash Course',
    type: 'course',
    category: 'Student Courses',
    price: 79,
    rating: 4.5,
    reviewsCount: 460,
    thumbnail: pics('co-03'),
    gallery: galleryPics('co-03'),
    description: 'Forces, energy and motion explained with demos you can try at home. Made for students who prefer seeing over memorizing.',
    features: ['8 hours, 28 lessons', 'Home experiments', 'Slow-motion demos', 'Problem walkthroughs', 'Cheat sheet PDF'],
    tags: ['physics', 'mechanics', 'science'],
    author: 'Theo Brooks',
    language: 'English',
    duration: '8h 00m',
    lessons: 28,
    level: 'Beginner',
    isFree: false,
    isFeatured: false,
    createdAt: '2024-05-20',
    accent: '#F59E0B',
  },
  {
    id: 'co-04',
    slug: 'spanish-a1-speak-from-day-one',
    title: 'Spanish A1 — Speak from Day One',
    type: 'course',
    category: 'Student Courses',
    price: 59,
    rating: 4.7,
    reviewsCount: 780,
    thumbnail: pics('co-04'),
    gallery: galleryPics('co-04'),
    description: 'Start speaking Spanish in your first hour. Everyday dialogues, shadowing and spaced recall keep it sticky.',
    features: ['15 hours, 36 lessons', 'Dialogues with transcripts', 'Shadowing practice', 'Anki deck included', 'Slow + native audio'],
    tags: ['spanish', 'languages', 'beginners'],
    author: 'Maya Njeri',
    language: 'English',
    duration: '15h 00m',
    lessons: 36,
    level: 'Beginner',
    isFree: false,
    isFeatured: false,
    createdAt: '2023-11-14',
    accent: '#F43F5E',
  },
  {
    id: 'co-05',
    slug: 'sat-math-intensive',
    title: 'SAT Math Intensive',
    type: 'course',
    category: 'Student Courses',
    price: 89,
    rating: 4.6,
    reviewsCount: 530,
    thumbnail: pics('co-05'),
    gallery: galleryPics('co-05'),
    description: 'A ten-hour sprint through the SAT math you actually need. Timed drills, error logs and a full practice test.',
    features: ['10 hours, 32 lessons', 'Timed drills', 'Error log template', 'Full practice test', 'Score predictor'],
    tags: ['sat', 'exam-prep', 'math'],
    author: 'Kai Robertson',
    language: 'English',
    duration: '10h 00m',
    lessons: 32,
    level: 'Intermediate',
    isFree: false,
    isFeatured: false,
    createdAt: '2024-08-12',
    accent: '#635BFF',
  },
  {
    id: 'co-06',
    slug: 'data-structures-in-javascript',
    title: 'Data Structures in JavaScript',
    type: 'course',
    category: 'Student Courses',
    price: 129,
    oldPrice: 169,
    rating: 4.4,
    reviewsCount: 390,
    thumbnail: pics('co-06'),
    gallery: galleryPics('co-06'),
    description: 'Arrays, queues, trees and graphs with JavaScript you can run. Visualize each step, then code it yourself.',
    features: ['14 hours, 38 lessons', 'Visual step-throughs', 'LeetCode-style tasks', 'Complexity notes', 'Interview prep pack'],
    tags: ['javascript', 'data-structures', 'algorithms'],
    author: 'Sofia Lind',
    language: 'English',
    duration: '14h 00m',
    lessons: 38,
    level: 'Intermediate',
    isFree: false,
    isFeatured: false,
    createdAt: '2024-01-28',
    accent: '#14B8A6',
  },
  {
    id: 'co-07',
    slug: 'linear-algebra-visualized',
    title: 'Linear Algebra Visualized',
    type: 'course',
    category: 'Student Courses',
    price: 79,
    rating: 4.3,
    reviewsCount: 280,
    thumbnail: pics('co-07'),
    gallery: galleryPics('co-07'),
    description: 'Vectors and matrices as shapes, not just numbers. See transformations move, then try them yourself.',
    features: ['9 hours, 30 lessons', 'Interactive visuals', 'Python notebooks', '3D transform demo', 'For graphics/ML starters'],
    tags: ['linear-algebra', 'math', 'visual'],
    author: 'Dr. Jun Park',
    language: 'English',
    duration: '9h 00m',
    lessons: 30,
    level: 'Intermediate',
    isFree: false,
    isFeatured: false,
    createdAt: '2023-07-02',
    accent: '#F59E0B',
  },
  {
    id: 'co-08',
    slug: 'learn-to-learn',
    title: 'Learn to Learn',
    type: 'course',
    category: 'Student Courses',
    price: 29,
    rating: 4.5,
    reviewsCount: 1120,
    thumbnail: pics('co-08'),
    gallery: galleryPics('co-08'),
    description: 'A student-friendly toolkit for focus, memory and steady progress. Small habits that make study feel lighter.',
    features: ['6 hours, 18 lessons', 'Focus and recall techniques', 'Weekly planner PDF', 'Habit tracker', 'For students 12+'],
    tags: ['learning', 'study-skills', 'focus'],
    author: 'Jun Park',
    language: 'English',
    duration: '6h 00m',
    lessons: 18,
    level: 'Beginner',
    isFree: false,
    isFeatured: false,
    createdAt: '2025-04-12',
    accent: '#635BFF',
  },
]

export const categories = [
  { slug: 'software', label: 'Software', count: 7, icon: '✦', color: '#635BFF', description: 'Tools that give good ideas more momentum.' },
  { slug: 'websites', label: 'Websites', count: 5, icon: '◈', color: '#14B8A6', description: 'Beautiful foundations for the web you want to make.' },
  { slug: 'open-source', label: 'Open Source', count: 6, icon: '⌘', color: '#F59E0B', description: 'Community-built tools, ready to explore and remix.' },
  { slug: 'books', label: 'Online Books', count: 10, icon: '▤', color: '#F43F5E', description: 'Ideas worth keeping close, on screen or off.' },
  { slug: 'kids', label: 'Kids Room', count: 8, icon: '✹', color: '#F59E0B', description: 'Big imagination for curious young minds.' },
  { slug: 'courses', label: 'Student Courses', count: 8, icon: '↗', color: '#6366F1', description: 'Learn something useful, one clear step at a time.' },
]

export const testimonials = [
  { quote: 'Regex Visual Debugger cut my code review time in half. I can finally explain my patterns to teammates.', name: 'Alex Rivera', role: 'Frontend lead at Finch', initials: 'AR' },
  { quote: 'Stellar SaaS saved a week of work. We shipped the marketing site on Monday and got our first demo Tuesday.', name: 'Priya Nair', role: 'Founder, Beamline', initials: 'PN' },
  { quote: 'Pragmatic TypeScript is the first JS book that made types feel practical, not academic.', name: 'Samir Patel', role: 'Full-stack developer', initials: 'SP' },
  { quote: 'Luna and the Sleepy Moon is now our nightly request. My daughter asks for the star garden every time.', name: 'Jordan Lee', role: 'Parent, Portland', initials: 'JL' },
  { quote: 'Python for Beginners got me from zero to my first script in a weekend. The projects actually finish.', name: 'Maya Chen', role: 'Student, Waterloo', initials: 'MC' },
  { quote: 'Drift Sync handled our offline logic in a day. No backend needed to start.', name: 'Casey Wu', role: 'Indie hacker', initials: 'CW' },
  { quote: 'The Quiet Manager gave me scripts for one-on-ones I actually use. My team noticed.', name: 'Rosa Delgado', role: 'Engineering manager', initials: 'RD' },
  { quote: 'SAT Math Intensive fixed my timing. Drills plus error log = +110 points.', name: 'Ibrahim Ali', role: 'High school senior', initials: 'IA' },
]

export const getProduct = (id?: string) => products.find((product) => product.id === id || product.slug === id)
export const getProductsByType = (type: ProductType) => products.filter((product) => product.type === type)
export const formatPrice = (price: number) => price === 0 ? 'Free' : `$${price}`
